---
- hosts: '{{ target }}'
  vars:
    http_port: 443
    max_clients: 200
  remote_user: root
  tasks:
  - name: install libselinux-python
    yum: pkg=libselinux-python state=present
  - name: ensure apache is at the latest version
    yum: pkg=httpd state=latest
  - name: write the apache config file
    template: src=index.html dest=/var/www/html/index.html
    notify:
    - restart apache
  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
  - name: chkconfig apache on
    command: /sbin/chkconfig httpd on


  handlers:
    - name: restart apache
      service: name=httpd state=restarted
