---
- hosts: '{{ target }}'
  remote_user: root
  tasks:
  - name: ACCEPT input on port 443
    command: /sbin/iptables -I INPUT 1 -p tcp --dport 443 -j ACCEPT
  - name: save iptables
    shell: /sbin/iptables-save > /etc/sysconfig/iptables
  
