---
- hosts: '{{ target }}'
  remote_user: root
  vars: 
   mysql_password: mysql_passwd 
  tasks:
  - name: Install MySQL packages 
    yum: name=mysql state=present
  - name: Install MySQL packages
    yum: name=mysql-server  state=present
  - name: Install Python mysqldb
    yum: name=MySQL-python state=present
  - name: ensure mysql is running
    service: name=mysqld state=started 
  - name: chkconfig mysql on
    command: /sbin/chkconfig mysqld on
   
  - name: Change root user password on first run
    mysql_user: name=root host={{ item }} password={{ mysql_password }} priv=*.*:ALL,GRANT
    with_items:
      - '{{ target }}' 
      - 127.0.0.1
      - ::1
      - localhost

  - name: add password to ~./my.cnf
    copy: src=my.cnf dest=/root/.my.cnf owner=root mode=0600

